version: '2'
services:
    koupona-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/koupona/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=koupona
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
